fbone/admin/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms import HiddenField, SubmitField, RadioField, DateField
from wtforms.validators import AnyOf

from ..user import USER_ROLE, USER_STATUS


class UserForm(Form):
    next = HiddenField()
    role_code = RadioField(u"Role", [AnyOf([str(val) for val in USER_ROLE.keys()])],
            choices=[(str(val), label) for val, label in USER_ROLE.items()])
    status_code = RadioField(u"Status", [AnyOf([str(val) for val in USER_STATUS.keys()])],
            choices=[(str(val), label) for val, label in USER_STATUS.items()])
    # A demo of datepicker.
    created_time = DateField(u'Created time')
    submit = SubmitField(u'Save')

fbone/__init__.py
# -*- coding: utf-8 -*-

from app import create_app

fbone/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

fbone/admin/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash
from flask.ext.login import login_required

from ..extensions import db
from ..decorators import admin_required

from ..user import User
from .forms import UserForm


admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/')
@login_required
@admin_required
def index():
    users = User.query.all()
    return render_template('admin/index.html', users=users, active='index')


@admin.route('/users')
@login_required
@admin_required
def users():
    users = User.query.all()
    return render_template('admin/users.html', users=users, active='users')


@admin.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        flash('User updated.', 'success')

    return render_template('admin/user.html', user=user, form=form)

fbone/api/__init__.py
# -*- coding: utf-8 -*-

from .views import api

fbone/api/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, current_app, request, jsonify
from flask.ext.login import login_user, current_user, logout_user

from ..user import User


api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/login', methods=['POST'])
def login():
    if current_user.is_authenticated():
        return jsonify(flag='success')

    username = request.form.get('username')
    password = request.form.get('password')
    if username and password:
        user, authenticated = User.authenticate(username, password)
        if user and authenticated:
            if login_user(user, remember='y'):
                return jsonify(flag='success')

    current_app.logger.debug('login(api) failed, username: %s.' % username)
    return jsonify(flag='fail', msg='Sorry, try again.')


@api.route('/logout')
def logout():
    if current_user.is_authenticated():
        logout_user()
    return jsonify(flag='success', msg='Logouted.')

fbone/app.py
# -*- coding: utf-8 -*-

import os

from flask import Flask, request, render_template
from flask.ext.babel import Babel

from .config import DefaultConfig
from .user import User, user
from .settings import settings
from .frontend import frontend
from .api import api
from .admin import admin
from .extensions import db, mail, cache, login_manager, oid
from .utils import INSTANCE_FOLDER_PATH


# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    frontend,
    user,
    settings,
    api,
    admin,
)


def create_app(config=None, app_name=None, blueprints=None):
    """Create a Flask app."""

    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name, instance_path=INSTANCE_FOLDER_PATH, instance_relative_config=True)
    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app


def configure_app(app, config=None):
    """Different ways of configurations."""

    # http://flask.pocoo.org/docs/api/#configuration
    app.config.from_object(DefaultConfig)

    # http://flask.pocoo.org/docs/config/#instance-folders
    app.config.from_pyfile('production.cfg', silent=True)

    if config:
        app.config.from_object(config)

    # Use instance folder instead of env variables to make deployment easier.
    #app.config.from_envvar('%s_APP_CONFIG' % DefaultConfig.PROJECT.upper(), silent=True)


def configure_extensions(app):
    # flask-sqlalchemy
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # flask-cache
    cache.init_app(app)

    # flask-babel
    babel = Babel(app)

    @babel.localeselector
    def get_locale():
        accept_languages = app.config.get('ACCEPT_LANGUAGES')
        return request.accept_languages.best_match(accept_languages)

    # flask-login
    login_manager.login_view = 'frontend.login'
    login_manager.refresh_view = 'frontend.reauth'

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)
    login_manager.setup_app(app)

    # flask-openid
    oid.init_app(app)


def configure_blueprints(app, blueprints):
    """Configure blueprints in views."""

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):

    @app.template_filter()
    def pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)


def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    if app.debug or app.testing:
        # Skip debug and test mode. Just check standard output.
        return

    import logging
    from logging.handlers import SMTPHandler

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'info.log')
    info_file_handler = logging.handlers.RotatingFileHandler(info_log, maxBytes=100000, backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    #app.logger.info("testing info.")
    #app.logger.warn("testing warn.")
    #app.logger.error("testing error.")

    mail_handler = SMTPHandler(app.config['MAIL_SERVER'],
                               app.config['MAIL_USERNAME'],
                               app.config['ADMINS'],
                               'O_ops... %s failed!' % app.config['PROJECT'],
                               (app.config['MAIL_USERNAME'],
                                app.config['MAIL_PASSWORD']))
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(mail_handler)


def configure_hook(app):
    @app.before_request
    def before_request():
        pass


def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/forbidden_page.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/page_not_found.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/server_error.html"), 500

fbone/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

fbone/frontend/views.py
# -*- coding: utf-8 -*-

from uuid import uuid4

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort)
from flask.ext.mail import Message
from flask.ext.babel import gettext as _
from flask.ext.login import login_required, login_user, current_user, logout_user, confirm_login, login_fresh

from ..user import User, UserDetail
from ..extensions import db, mail, login_manager, oid
from .forms import SignupForm, LoginForm, RecoverPasswordForm, ReauthForm, ChangePasswordForm, OpenIDForm, CreateProfileForm


frontend = Blueprint('frontend', __name__)


@frontend.route('/login/openid', methods=['GET', 'POST'])
@oid.loginhandler
def login_openid():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = OpenIDForm()
    if form.validate_on_submit():
        openid = form.openid.data
        current_app.logger.debug('login with openid(%s)...' % openid)
        return oid.try_login(openid, ask_for=['email', 'fullname', 'nickname'])
    return render_template('frontend/login_openid.html', form=form, error=oid.fetch_error())


@oid.after_login
def create_or_login(resp):
    user = User.query.filter_by(openid=resp.identity_url).first()
    if user and login_user(user):
        flash('Logged in', 'success')
        return redirect(oid.get_next_url() or url_for('user.index'))
    return redirect(url_for('frontend.create_profile', next=oid.get_next_url(),
            name=resp.fullname or resp.nickname, email=resp.email,
            openid=resp.identity_url))


@frontend.route('/create_profile', methods=['GET', 'POST'])
def create_profile():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = CreateProfileForm(name=request.args.get('name'),
            email=request.args.get('email'),
            openid=request.args.get('openid'))

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()

        if login_user(user):
            return redirect(url_for('user.index'))

    return render_template('frontend/create_profile.html', form=form)


@frontend.route('/')
def index():
    current_app.logger.debug('debug')

    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    page = int(request.args.get('page', 1))
    pagination = User.query.paginate(page=page, per_page=10)
    return render_template('index.html', pagination=pagination)


@frontend.route('/search')
def search():
    keywords = request.args.get('keywords', '').strip()
    pagination = None
    if keywords:
        page = int(request.args.get('page', 1))
        pagination = User.search(keywords).paginate(page, 1)
    else:
        flash(_('Please input keyword(s)'), 'error')
    return render_template('frontend/search.html', pagination=pagination, keywords=keywords)


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)

        if user and authenticated:
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):
                flash(_("Logged in"), 'success')
            return redirect(form.next.data or url_for('user.index'))
        else:
            flash(_('Sorry, invalid login'), 'error')

    return render_template('frontend/login.html', form=form)


@frontend.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(_('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(_('Password is wrong.'), 'error')
    return render_template('frontend/reauth.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


@frontend.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = SignupForm(next=request.args.get('next'))

    if form.validate_on_submit():
        user = User()
        user.user_detail = UserDetail()
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        if login_user(user):
            return redirect(form.next.data or url_for('user.index'))

    return render_template('frontend/signup.html', form=form)


@frontend.route('/change_password', methods=['GET', 'POST'])
def change_password():
    user = None
    if current_user.is_authenticated():
        if not login_fresh():
            return login_manager.needs_refresh()
        user = current_user
    elif 'activation_key' in request.values and 'email' in request.values:
        activation_key = request.values['activation_key']
        email = request.values['email']
        user = User.query.filter_by(activation_key=activation_key) \
                         .filter_by(email=email).first()

    if user is None:
        abort(403)

    form = ChangePasswordForm(activation_key=user.activation_key)

    if form.validate_on_submit():
        user.password = form.password.data
        user.activation_key = None
        db.session.add(user)
        db.session.commit()

        flash(_("Your password has been changed, please log in again"),
              "success")
        return redirect(url_for("frontend.login"))

    return render_template("frontend/change_password.html", form=form)


@frontend.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash('Please see your email for instructions on '
                  'how to access your account', 'success')

            user.activation_key = str(uuid4())
            db.session.add(user)
            db.session.commit()

            url = url_for('frontend.change_password', email=user.email, activation_key=user.activation_key, _external=True)
            html = render_template('macros/_reset_password.html', project=current_app.config['PROJECT'], username=user.name, url=url)
            message = Message(subject='Reset your password in ' + current_app.config['PROJECT'], html=html, recipients=[user.email])
            mail.send(message)

            return render_template('frontend/reset_password.html', form=form)
        else:
            flash(_('Sorry, no user found for that email address'), 'error')

    return render_template('frontend/reset_password.html', form=form)


@frontend.route('/help')
def help():
    return render_template('frontend/footers/help.html', active="help")

fbone/settings/__init__.py
# -*- coding: utf-8 -*-

from .views import settings

fbone/user/__init__.py
# -*- coding: utf-8 -*-

from .models import UserDetail, User
from .views import user
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

fbone/user/views.py
# -*- coding: utf-8 -*-

import os

from flask import Blueprint, render_template, send_from_directory, abort
from flask import current_app as APP
from flask.ext.login import login_required, current_user

from .models import User


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/')
@login_required
def index():
    if not current_user.is_authenticated():
        abort(403)
    return render_template('user/index.html', user=current_user)


@user.route('/<int:user_id>/profile')
def profile(user_id):
    user = User.get_by_id(user_id)
    return render_template('user/profile.html', user=user)


@user.route('/<int:user_id>/avatar/<path:filename>')
@login_required
def avatar(user_id, filename):
    dir_path = os.path.join(APP.config['UPLOAD_FOLDER'], 'user_%s' % user_id)
    return send_from_directory(dir_path, filename, as_attachment=True)

fbone/templates/macros/_ask_user_to_update_ie.html
<!--[if lt IE 7]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

fbone/templates/macros/_form.html
{% macro render_checkbox(field) %}
<div class="checkbox{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id }}">
        {{ field }}{{ field.label.text }}
    </label>
    <span class="help-inline">{{ field.description }}</span>
    {% if field.errors -%}
    <ul class="help-block">
        {% for error in field.errors -%}
        <li>{{ error|e }}</li>
        {%- endfor %}
    </ul>
    {%- endif %}
</div>
{% endmacro%}

{% macro render_radio(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    {{ field.label(class_="control-label") }}
    <div class="">
        {% for subfield in field -%}
        <label for="{{ subfield.id }}" class="radio-inline">
            {{ subfield }} {{ subfield.label.text }}
        </label>
        {%- endfor %}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_datepicker(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field() }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_textarea(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control", rows="4") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_file(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_input(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_action(field) %}
<div class="form-group">
    <div class="form-actions">
        {{ field(class_="btn btn-primary") }}
    </div>
</div>
{% endmacro %}

{% macro render_form(url, form, horizontal=False, legend=None, confirm_msg=None, formid=None) %}
{% set idattr = "id=" + formid if formid else "" %}
<form {{idattr}} class="{% if horizontal %}form-horizontal{% endif %}" method="POST" action="{{ url }}"
    {% if confirm_msg %}onsubmit='return confirm("{{ confirm_msg }}");' {% endif %} 
    {% if form.multipart %}enctype="multipart/form-data"{% endif %} >
    {{ form.hidden_tag() }}
        {% if legend %}
        <legend>{{ legend|safe }}</legend>
        {% endif %}
        {% set focus = True %}
        {% for field in form %}
            {% if field.type != "HiddenField" and field.type != "CSRFTokenField" %}
                {% if field.type == "RadioField" %}
                    {{ render_radio(field) }}
                {% elif field.type == "BooleanField" %}
                    {{ render_checkbox(field) }}
                {% elif field.type == "SubmitField" %}
                    {{ render_action(field) }}
                {% elif field.type == "TextAreaField" %}
                    {{ render_textarea(field) }}
                {% elif field.type == "DateField" %}
                    {{ render_datepicker(field) }}
                {% elif field.type == "FileField" %}
                    {{ render_file(field) }}
                {% elif field.type == "TextField" %}
                    {% if focus %}
                        {{ render_input(field) }}
                        {% set focus = False %}
                    {% else %}
                        {{ render_input(field) }}
                    {% endif %}
                {% else %}
                    {{ render_input(field) }}
                {% endif %}
            {% endif %}
        {% endfor %}
</form>
{% endmacro %}

fbone/templates/macros/_google_analytics.html
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X');ga('send','pageview');
</script>

fbone/templates/macros/_misc.html
{% macro render_user_table(users, class='') %}
<table class='{{ class }}'>
    <thead>
        <tr>
            <td>#</td>
            <td>Username</td>
            <td>Email</td>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ loop.index }}</td>
            <td><a href="{{ url_for('user.profile', name=user.name) }}">{{ user.name }}</a></td>
            <td>{{ user.email }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endmacro %}

{% macro render_pagination(pagination, endpoint) %}
    {% if pagination.pages > 1 %}
        <div class='pagination'>
            <ul>
                <li class="prev {% if not pagination.has_prev %}disabled{% endif %}"><a href="{{ url_for(endpoint, page=pagination.page-1) }}">&larr; Previous</a></li>
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        <li class='{% if page == pagination.page %}active{% endif %}'>
                            <a href='{{ url_for(endpoint, page=page) }}'>{{ page }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a href='#'>...</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="next {% if not pagination.has_next %}disabled{% endif %}"><a href="{{ url_for(endpoint, page=pagination.page+1) }}">Next &rarr;</a></li>
            </ul>
        </div>
    {% endif %}
{% endmacro %}

fbone/templates/macros/_reset_password.html
<p>Forgot your password, {{ username }}?</p>

<p>{{ project }} received a request to reset the password for your {{ project }} account {{ username }}.</p>

<p>If you want to reset your password, click on the link below (or copy and paste the URL into your browser):</p>

<a href="{{ url }}">Click to Reset Password</a>

<p>This link takes you to a secure page where you can change your password. For tips on selecting a strong password, see our Safe Tweeting help page.</p>

<p>If you don't want to reset your password, please ignore this message. Your password will not be reset. If you have any concerns, please contact us at {{ project }} Support.</p>

<p>The {{ project }} Team</p>